CatDatingSite/CatDatingSite/Controllers/CatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CatDatingSite.Controllers

{
     using System.Data.Entity;
     using CatDatingSite.Models;
      using System.Net;
    using System.IO;

    public class CatsController : Controller
    {
        // GET: Cats
        public ActionResult Index()
        {
            using (var catDb = new catDb())
            {
                //iegut kaku sarakstu no kaku datubazes tabulas
                var catList = catDb.CatProfiles.Include(catProf => catProf.ProfilePicture).ToList();
                //izveidot skatu tam ieksa padodot kaku sarakstu
                return View(catList);
            }
        }

        public ActionResult AddCat()
        {
            return View();
        }
        public ActionResult GetCatProfilePicture(int catProfilePictureId)
        {
            using (var db = new catDb())
            {
                var profilePic = db.Files.First(rec => rec.FileId == catProfilePictureId);
                return File(profilePic.Content, profilePic.ContentType);
            }
        }


        [HttpPost]
        public ActionResult AddCat(CatProfile userCreatedCat)

        {
            if (ModelState.IsValid == false)
            {
                return View(userCreatedCat);
            }
            // izveido savienojumu ar datu bazi
            using (var catDb = new catDb())
            {
                catDb.CatProfiles.Add(userCreatedCat);
                catDb.SaveChanges();
                return RedirectToAction("Index");
            }
        }


       


        [HttpPost]
        public ActionResult EditCat(CatProfile catProfile, HttpPostedFileBase uploadedPicture)
        {
            if (ModelState.IsValid == false)
            {
                return View(catProfile);
            }

            using (var catDb = new catDb())
            {
                // ja ir pievienota profila bilde
                if (uploadedPicture != null)
                {
                    // atrodam šobrīdējo bildi, ja tāda ir
                    var currentPic = catDb.Files.FirstOrDefault(fileRecord => fileRecord.CatProfileId == catProfile.CatId);
                    if (currentPic != null)
                    {
                        catDb.Files.Remove(currentPic);
                    }

                    // izveidojam jaunu profila bildes datubāzes eksemplāru, ko ierakstīsim datubāzē
                    var profilePic = new Models.File();

                    // saglabājam bildes faila nosaukumu
                    profilePic.FileName = Path.GetFileName(uploadedPicture.FileName);

                    // saglabājam bildes tipu
                    profilePic.ContentType = uploadedPicture.ContentType;

                    // izmantojam BinaryReader lai pārvērstu bildi baitos
                    using (var reader = new BinaryReader(uploadedPicture.InputStream))
                    {
                        // saglabājam baitus datubāzes ierakstā
                        profilePic.Content = reader.ReadBytes(uploadedPicture.ContentLength);
                    }

                    // pasakam profila bildei, kurš kaķa profils ir kaķa profils, kam šī bilde pieder
                    profilePic.CatProfileId = catProfile.CatId;
                    profilePic.CatProfile = catProfile;

                    // pievienojam profila bildes datubāzes ierakstu Files tabulai
                    catDb.Files.Add(profilePic);

                    // paskam kaķu profilam, kas ir viņa profila bilde
                    catProfile.ProfilePicture = profilePic;
                }

                // pievienot using System.Data.Entity;
                catDb.Entry(catProfile).State = EntityState.Modified;
                catDb.SaveChanges();
            }

            // pavēlam browserim atgriezties Index lapā (t.i. pārlādēt to)
            return RedirectToAction("Index");
        }

        public ActionResult EditCat(int editableCatId)
        {
            using (var catDb = new catDb())
            {
                var editableCat = catDb.CatProfiles.Include(catRecord => catRecord.ProfilePicture).First(catProfile => catProfile.CatId == editableCatId);
                return View("EditCat", editableCat);
            }
        }
    
    public ActionResult DeleteCats(int catId)


    {
        using (var catDb = new catDb())
        {
            //atrast kaki, kam pieder noraditais idenfikators
            var deleteableCat = catDb.CatProfiles.First(catProfile => catProfile.CatId == catId);
            // izdzēst šo kaki no tabulas 
            catDb.CatProfiles.Remove(deleteableCat);
            //saglab'at veikt'as izmai'nas
            catDb.SaveChanges();
        }
        //japievieno using system.net
        //atgriezam rezultatu kad darbiba ir veiksmiga
        // liekam browserim atgriezties index lapā (t.i parlādēt to )
        return RedirectToAction("Index");
    }



    public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CatDatingSite/CatDatingSite/Views/Cats/AddCat.cshtml
@model CatDatingSite.Models.CatProfile
@{
	/**/

	ViewBag.Title = "AddCat";
}

<h2>AddCat</h2>
@using (Html.BeginForm("AddCat", "Cats", FormMethod.Post))
{
	<div class="row">
		<div class="col-md-6">Cat name</div>
		<div class="col-md-6">@Html.EditorFor(Model => Model.CatName)</div>
	</div>

	<div class="row">
		<div class="col-md-6">Cat age</div>
		<div class="col-md-6">@Html.EditorFor(Model => Model.CatAge)</div>
	</div>

	<div class="row">
		<div class="col-md-6">Cat image</div>
		<div class="col-md-6">@Html.EditorFor(Model => Model.CatImage)</div>
	</div>

	<div class="row">
		<div class="col-md-6">Cat description</div>
		<div class="col-md-6">@Html.EditorFor(Model => Model.CatDescription)</div>
		<p>@Html.ValidationMessageFor(Model => Model.CatDescription)</p>
	</div>

	<input type="submit" value="Izveidot kaķi" />
}

CatDatingSite/CatDatingSite/Views/Cats/EditCat.cshtml
@model CatDatingSite.Models.CatProfile
@{
	/**/

	ViewBag.Title = "EditCat";
}

<h2>Edit Cat</h2>
@using (Html.BeginForm("EditCat", "Cats", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
	@Html.HiddenFor(Model => Model.CatId)

	<div class="form-horizontal">
		<div class="form-group">
			@Html.LabelFor(model => model.CatName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(Model => Model.CatName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CatName, "", new { @class = "text-danger" })
			</div>
		</div>

	</div>

	<div class="form-horizontal">
		<div class="form-group">
			@Html.LabelFor(model => model.CatAge, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(Model => Model.CatAge, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CatAge, "", new { @class = "text-danger" })
			</div>
		</div>

	</div>


	<div class="form-horizontal">
		<div class="form-group">
			@Html.LabelFor(model => model.CatDescription, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(Model => Model.CatDescription, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.CatDescription, "", new { @class = "text-danger" })
			</div>
		</div>

	</div>
	<div class="form-horizontal">
		kaķa attēls
			<div class="col-md-10">
				<input type="file" id="uploadPicture" name="uploadPicture" />
			</div>
		</div>

	
	<input type="submit" value="Saglabāt izmaiņas kaķī" />
}

CatDatingSite/CatDatingSite/Views/Cats/Index.cshtml
@model List<CatDatingSite.Models.CatProfile>

<div class="container">
	<div class="row">
		@Html.ActionLink("pievienot jaunu kaķi", "AddCat", "Cats", htmlAttributes: new { @class = "btn btn-info", role = "button" })
	</div>
</div>


<!-- kad vēlamies izsaukt C# kodu, lietojam at simbolu -->
@foreach (var cat in Model)
{

	<div class="row">
		<div class="col-md-12">

			<h2>Cat name: @cat.CatName</h2>
			<p> Cat age is @cat.CatAge</p>
			<!-- CatsController -> GetCatProfilePicture (catProfilePictureId)
			/Cats/GetCatProfilePicture?catProfilePictureId=5 -->
			@if (cat.ProfilePicture != null)
			{
				<img src="~/Cats/GetCatProfilePicture?catProfilePictureId=@cat.ProfilePicture.CatProfileId" class="img-responsive" />
			}
			<p>
				@cat.CatDescription
			</p>
			<p>
				@Html.ActionLink("Rediģēt kaķi", "EditCat", "Cats", new { editableCatId = cat.CatId }, htmlAttributes: new { @class = "btn btn-info", role = "button" })
				@Html.ActionLink("Nodzēst kaķi", "DeleteCats", "Cats", new { deletableCatId = cat.CatId }, htmlAttributes: new { @class = "btn btn-info", role = "button" })
			</p>
		</div>
	</div>
}